// import applogo from "../assets/images/logo.png";
// import newlogo from "../assets/images/newlogo.png";

import {
  LockOutlined,
  Close,
  Save,
  Menu,
  Inbox,
  Mail,
  Newspaper,
  MapsHomeWork,
  Inventory,
  BarChart,
  ReceiptLong,
  Report,
  Edit,
  Person,
  Dashboard,
  People,
  CreditCard,
  Description,
  ExitToApp,
  Settings,
  ManageAccounts,
  LockReset,
  Diversity3,
  AccountCircle,
} from "@mui/icons-material";

import { moduleitems, configuration } from "./moduleitems";

export {
  LockOutlined as LockOutlinedIcon,
  Close as CloseIcon,
  Save as SaveIcon,
  Menu as MenuIcon,
  Inbox as InboxIcon,
  Mail as MailIcon,
  Newspaper as NewspaperIcon,
  MapsHomeWork as MapsHomeWorkIcon,
  Inventory as InventoryIcon,
  BarChart as BarChartIcon,
  ReceiptLong as ReceiptLongIcon,
  Report as ReportIcon,
  Edit as EditIcon,
  Person as PersonIcon,
  Dashboard as DashboardIcon,
  People as PeopleIcon,
  CreditCard as CreditCardIcon,
  Description as DescriptionIcon,
  ExitToApp as ExitToAppIcon,
  Settings as SettingsIcon,
  ManageAccounts as ManageAccountsIcon,
  LockReset as LockResetIcon,
  Diversity3 as Diversity3Icon,
  AccountCircle as AccountCircleIcon,
  moduleitems,
  configuration,
};
